postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "inject-securly"
  database: "postgres"
  
server:
  port: ":8080"

containerRepo:
  url: "https://hub.docker.com"
  username: "rajeshd2090"
  password: "provide-securly"